<div class="home-main-image">
    <div class="home-wrapper">
        <div class="page-box fadeInUp">
            <div class="text1">Mentour</div>
                <div class="text2">Mentor matching simplified</div>
                <div class="mgt50"><a href="search.php" class="btn1 btn-big">Find your mentor or mentee</a></div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="home-mentour-text">Mentours</div>
        <div class="col-lg-6">
            <div class="col-md-6 home-featured-mentour">
                <img src="http://students.washington.edu/xulizhou/info_capstone/final_version/images/home/u42.jpg" alt="pc1" style="width:174px;height:174px;"/>
                <div class="tt">Samantha Wong</div>
                <div class="intro">MBA Instructor at UW Foster School of Business. She has excellent student ratings</div>
            </div>
            <div class="col-md-6 home-featured-mentour">
                <img src="http://students.washington.edu/xulizhou/info_capstone/final_version/images/home/u44.jpg" alt="pc2" style="width:174px;height:174px;"/>
                <div class="tt">Kevin Kim</div>
                <div class="intro"> PhD Candidate in Math at UW. He is also a Math table teaching math 126, 307, 308</div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="col-md-6 home-featured-mentour">
                <img src="http://students.washington.edu/xulizhou/info_capstone/final_version/images/home/u46.png" alt="pc2" style="width:174px;height:174px;"/>
                <div class="tt">Tyler Spencer</div>
                <div class="intro"> Works as an IT Analyst at Deloitte Digital after he graduated Magna Cum Laude from UW in informatics</div>
            </div>
            <div class="col-md-6 home-featured-mentour">
                <img src="http://students.washington.edu/xulizhou/info_capstone/final_version/images/home/u48.jpg" alt="pc2" style="width:174px;height:174px;"/>
                <div class="tt">Peter Black</div>
                <div class="intro"> Worked at Amazon in Marketing Service for about 5 years, after graduating from UW Foster School</div>
            </div>
        </div>
    </div>
    <div class="row">
    <div class="home-mentour-text">How Mentour Works</div>
        <div class="col-lg-6">
            <div class="col-md-6 home-featured-mentour">
                <img src="images/signup.png" alt="pc1" style="width:174px;height:174px;">
                <div class="tt">Signup</div>
            </div>
            <div class="col-md-6 home-featured-mentour">
                <img src="images/createprofile.png" alt="pc2" style="width:174px;height:174px;">
                <div class="tt">Create a profile</div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="col-md-6 home-featured-mentour">
                <img src="images/search.png" alt="pc2" style="width:174px;height:174px;">
                <div class="tt">Search profiles</div>
            </div>
            <div class="col-md-6 home-featured-mentour">
                <img src="images/contact.png" alt="pc2" style="width:174px;height:174px;">
                <div class="tt">Contact mentor/mentee</div>
            </div>
        </div>
    </div>
</div>